env:
  es2021: true
  node: true
extends:
- airbnb-base
- airbnb-typescript/base
- prettier
- standard-with-typescript
- standard-with-typescript
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', 'prettier']
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json

rules: {
  "semi": "off",
  "max-len": "off",
  "import/prefer-default-export": "off",
  "no-await-in-loop": "off",
  "no-restricted-syntax": "off",
  "class-methods-use-this": "off",
  "no-param-reassign": "off",
  '@typescript-eslint/restrict-template-expressions': 'off'
}
